apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-mgmt.name" . }}
  labels:
    {{- include "llm-mgmt.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "llm-mgmt.selectorLabels" . | nindent 4 }}
  ports:
    - {name: http, port: 8086, targetPort: http}
    - {name: machine, port: 8087, targetPort: machine}
